export const KEEP_GOING_QUOTES: readonly string[] = [
  "Tomorrow is a new opportunity to be better than you were today.",
  "Every setback is a setup for a comeback.",
  "Progress isn't linear. Keep showing up.",
  "The only failure is giving up. You're still in the game.",
  "Small steps forward are still steps forward.",
  "Your commitment to try again is what matters most.",
  "Success is built on a foundation of well-handled failures.",
  "It's not about being perfect, it's about being persistent.",
  "Today didn't go as planned. Tomorrow is yours to shape.",
  "The difference between who you are and who you want to be is what you do.",
  "Discipline is choosing between what you want now and what you want most.",
  "You're not starting over, you're starting with experience.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "Your future self is counting on the choices you make tomorrow.",
  "Consistency beats perfection every time.",
  "One day at a time. One choice at a time.",
  "The comeback is always stronger than the setback.",
  "You didn't come this far to only come this far.",
  "Fall seven times, stand up eight.",
  "What you do today can improve all your tomorrows.",
  "Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up. - Galatians 6:9",
  "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future. - Jeremiah 29:11",
  "I can do all things through Christ who strengthens me. - Philippians 4:13",
  "The Lord is my strength and my shield; my heart trusts in him, and he helps me. - Psalm 28:7",
  "Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go. - Joshua 1:9",
  "Therefore we do not lose heart. Though outwardly we are wasting away, yet inwardly we are being renewed day by day. - 2 Corinthians 4:16",
  "But those who hope in the Lord will renew their strength. They will soar on wings like eagles. - Isaiah 40:31",
  "Consider it pure joy whenever you face trials, because you know that the testing of your faith produces perseverance. - James 1:2-3",
  "Commit to the Lord whatever you do, and he will establish your plans. - Proverbs 16:3",
  "The steadfast love of the Lord never ceases; his mercies never come to an end; they are new every morning. - Lamentations 3:22-23",
  "And we know that in all things God works for the good of those who love him. - Romans 8:28",
  "Forgetting what is behind and straining toward what is ahead, I press on toward the goal. - Philippians 3:13-14",
  "Do not despise these small beginnings, for the Lord rejoices to see the work begin. - Zechariah 4:10",
  "The Lord himself goes before you and will be with you; he will never leave you nor forsake you. - Deuteronomy 31:8",
  "Trust in the Lord with all your heart and lean not on your own understanding. - Proverbs 3:5",
  "He gives strength to the weary and increases the power of the weak. - Isaiah 40:29",
  "Start children off on the way they should go, and even when they are old they will not turn from it. - Proverbs 22:6",
  "No discipline seems pleasant at the time, but painful. Later on, however, it produces a harvest of righteousness. - Hebrews 12:11",
  "Whatever you do, work at it with all your heart, as working for the Lord. - Colossians 3:23",
  "The Lord is close to the brokenhearted and saves those who are crushed in spirit. - Psalm 34:18",
];

export const getRandomQuote = (): string =>
  KEEP_GOING_QUOTES[Math.floor(Math.random() * KEEP_GOING_QUOTES.length)];
